### PR TITLE
Fix feature flags tests with missing distinct ID

### PR DESCRIPTION
**Pull request by liyiy**
Feature flag tests were failing because there was no distinct ID being set

### CODE REVIEW

**Review by EDsCODE — APPROVED** [review]

**Comment by neilkakkar** [comment]
there should be anon IDs though which are automatically generated? 🤔

**Comment by EDsCODE** [comment]
Seems like the identify is triggering a refresh that otherwise isn't happening..

**Comment by EDsCODE** [comment]
Here's the weird gotcha: https://github.com/PostHog/posthog-android/blob/master/posthog/src/main/java/com/posthog/android/PostHogFeatureFlags.java#L156

Decide not hit unless identify happens first. Should this be the pattern for posthog-android?

**Comment by liyiy** [comment]
> there should be anon IDs though which are automatically generated? 🤔

There is an anon ID

**Comment by liyiy** [comment]
> Here's the weird gotcha: https://github.com/PostHog/posthog-android/blob/master/posthog/src/main/java/com/posthog/android/PostHogFeatureFlags.java#L156
> 
> Decide not hit unless identify happens first. Should this be the pattern for posthog-android? Otherwise the fix would be to remove the line above and change it so that the decide payload will pass anonId as distinct_id if there is no distinct_id set

```remove the line above and change it so that the decide payload will pass anonId as distinct_id if there is no distinct_id set```

Right, just making sure ^ is the standard, idk what the standard is between all the libraries sometimes

**Comment by neilkakkar** [comment]
Some apps don't have logins/ are privacy protected, where the implementors will never call `identify()`, so we should support flags without identify in android too :) - it's the common standard across all libs, great job catching this issue!

**Pull request merged**
