### PR TITLE
flush forcefully sends events regardless the delay

### PR DESCRIPTION
**Pull request by marandaneto**
## :bulb: Motivation and Context
https://github.com/postHog/posthog-js-lite/ sends events regardless the timer if `flush` is called manually.

https://posthog.com/questions/flush-interval-seconds-not-working

## :pencil: Checklist

- [X] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [X] No breaking change or entry added to the changelog.

### CODE REVIEW

**Review by benjackwhite — COMMENTED** [review]
I can't tell from the PR alone but I can at least clarify how it works elsewhere:

1. By default events are queued and are only flushed as a batch once a timer passes or the size threshold is hit.
2. However, a user can manually call the `flush` function to force whatever is in the buffer to be flushed.

If this code achieves that then 👍

**Review by pauldambra — APPROVED** [review]
🚢

**Comment by marandaneto** [comment]
> I can't tell from the PR alone but I can at least clarify how it works elsewhere:
> 
> 1. By default events are queued and are only flushed as a batch once a timer passes or the size threshold is hit.
> 2. However, a user can manually call the `flush` function to force whatever is in the buffer to be flushed.
> 
> If this code achieves that then 👍

1. not really, since its an `and` operation, the timer passes `and` the threshold hits.
2. yes, this PR addresses this use case.

**Comment by marandaneto** [comment]
> > I can't tell from the PR alone but I can at least clarify how it works elsewhere:
> > 
> > 1. By default events are queued and are only flushed as a batch once a timer passes or the size threshold is hit.
> > 2. However, a user can manually call the `flush` function to force whatever is in the buffer to be flushed.
> > 
> > If this code achieves that then 👍
> 
> 1. not really, since its an `and` operation, the timer passes `and` the threshold hits.
> 2. yes, this PR addresses this use case.

made new commits that address the 1. item, if this ever becomes a battery-draining issue, we can revert this part since its super simple.

**Pull request merged**
